### PR TITLE
Fix for Push Notifications

### LINKED ISSUE #30: Push notification break
Currently, the push notification feature is not working. Further research indicates that if the manifest file is not located in the root directory, the push notification will not work properly.

### PR DESCRIPTION
**Pull request by andreszorro**
Fixes #30. Also organizing some code and doing some cleanup.

### CODE REVIEW

**Comment by andreszorro** [comment]
Can't see code climate bugs. Seems to be a private URL.

File: source/index.js [hunk 1]
```diff
@@ -272,8 +269,25 @@ app.get('/sync-user', (req, res) => {
   }
 });
 
+if (CONFIG.NODE_ENV === 'development') {
+  // allows service worker to run
+  // In prod, this is handled by nginx
+  app.use((req, res, next) => {
+    res.setHeader('Service-Worker-Allowed', CONFIG.ROOT_URI || '/');
```
Comment (oagarcia) [inline source/index.js]: Great! good catch! Didn't note the header path was not updated! Hope this fixes the push feature

File: web/scripts/main.js [hunk 2]
```diff
@@ -18,114 +18,123 @@ const PenguinReport = {
...
-                console.log('Looks like there was a problem. Status Code: ' + response.status);
-                throw new Error();
-              }
-              return response.json().then((data) => {
-                console.log('the data', data);
-              }).catch((err) => {
-                console.error('Unable to retrieve data', err);
-              });
-            });
+    // Applying DeMorgan's Law here to avoid nesting
```
Comment (oagarcia) [inline web/scripts/main.js]: Nice refactor!
